-- Project Axiom: GDPR-Compliant Analytics Schema
-- Optimized for Supabase/PostgreSQL

CREATE TABLE IF NOT EXISTS page_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id UUID NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  path TEXT NOT NULL,
  referrer TEXT,
  browser_type TEXT,
  width INTEGER,
  
  -- Strict Privacy: NO field for IP addresses
  -- Strict Privacy: NO field for User-Agents
  -- All metrics are anonymized and aggregated by the Axiom Brain.
  
  CONSTRAINT valid_path CHECK (length(path) > 0)
);

-- Enable Real-Time Monitoring
ALTER PUBLICATION supabase_realtime ADD TABLE page_events;

-- Indexing for performance
CREATE INDEX IF NOT EXISTS idx_site_events ON page_events (site_id, timestamp DESC);
